### ISSUE TITLE
td-client-java continues to retry login with bad apiKey

### ISSUE THREAD

**Issue by rockpunk** [treasure-data/td-client-java#12]
Hey Muga!

We noticed a while back that if you try running submitJob() with a bad client API Key, then submitJob just continues to retry giving these log messages:

22:26:40.346 [main] DEBUG c.m.c.plugin.treasuredata.Settings - Using API Key: badKey
22:26:40.349 [main] DEBUG c.m.c.plugin.treasuredata.Runner - Connecting to TreasureData
22:26:40.372 [main] DEBUG c.m.c.plugin.treasuredata.Runner - Submitting treasure data job against td db: testdb
Nov 24, 2015 10:26:42 PM com.treasure_data.client.DefaultClientAdaptorImpl doSubmitJob
SEVERE: Submit job failed, response message = Unauthorized, code = 401
Nov 24, 2015 10:26:42 PM com.treasure_data.client.DefaultClientAdaptorImpl doSubmitJob
SEVERE: {"error":"Failed to Login"}
Nov 24, 2015 10:26:42 PM com.treasure_data.client.DefaultClientAdaptorImpl submitJob
WARNING: It failed. but will be retried: Submit job failed, response message = Unauthorized, detail = {"error":"Failed to Login"}, code = 401
Nov 24, 2015 10:26:45 PM com.treasure_data.client.DefaultClientAdaptorImpl doSubmitJob
SEVERE: Submit job failed, response message = Unauthorized, code = 401
Nov 24, 2015 10:26:45 PM com.treasure_data.client.DefaultClientAdaptorImpl doSubmitJob
SEVERE: {"error":"Failed to Login"}
Nov 24, 2015 10:26:45 PM com.treasure_data.client.DefaultClientAdaptorImpl submitJob
WARNING: It failed. but will be retried: Submit job failed, response message = Unauthorized, detail = {"error":"Failed to Login"}, code = 401
Nov 24, 2015 10:26:54 PM com.treasure_data.client.DefaultClientAdaptorImpl doSubmitJob
SEVERE: Submit job failed, response message = Unauthorized, code = 401
Nov 24, 2015 10:26:54 PM com.treasure_data.client.DefaultClientAdaptorImpl doSubmitJob
SEVERE: {"error":"Failed to Login"}
Nov 24, 2015 10:26:54 PM com.treasure_data.client.DefaultClientAdaptorImpl submitJob
WARNING: It failed. but will be retried: Submit job failed, response message = Unauthorized, detail = {"error":"Failed to Login"}, code = 401
Nov 24, 2015 10:27:04 PM com.treasure_data.client.DefaultClientAdaptorImpl doSubmitJob
SEVERE: Submit job failed, response message = Unauthorized, code = 401
Nov 24, 2015 10:27:04 PM com.treasure_data.client.DefaultClientAdaptorImpl doSubmitJob
SEVERE: {"error":"Failed to Login"}
Nov 24, 2015 10:27:04 PM com.treasure_data.client.DefaultClientAdaptorImpl submitJob
WARNING: It failed. but will be retried: Submit job failed, response message = Unauthorized, detail = {"error":"Failed to Login"}, code = 401
Nov 24, 2015 10:27:22 PM com.treasure_data.client.DefaultClientAdaptorImpl doSubmitJob
SEVERE: Submit job failed, response message = Unauthorized, code = 401
Nov 24, 2015 10:27:22 PM com.treasure_data.client.DefaultClientAdaptorImpl doSubmitJob
SEVERE: {"error":"Failed to Login"}
Nov 24, 2015 10:27:22 PM com.treasure_data.client.DefaultClientAdaptorImpl submitJob
WARNING: It failed. but will be retried: Submit job failed, response message = Unauthorized, detail = {"error":"Failed to Login"}, code = 401
Nov 24, 2015 10:27:56 PM com.treasure_data.client.DefaultClientAdaptorImpl doSubmitJob
SEVERE: Submit job failed, response message = Unauthorized, code = 401
Nov 24, 2015 10:27:56 PM com.treasure_data.client.DefaultClientAdaptorImpl doSubmitJob
SEVERE: {"error":"Failed to Login"}
Nov 24, 2015 10:27:56 PM com.treasure_data.client.DefaultClientAdaptorImpl submitJob
WARNING: It failed. but will be retried: Submit job failed, response message = Unauthorized, detail = {"error":"Failed to Login"}, code = 401

It may eventually fail, but since the wait time progressively gets longer, the effect is that the submitJob request just fails with no useful error message. 

If authentication returns a 401, I think submitJob should fail immediately.

**Comment by xerial** [comment]
Hi,
 
Could you try a brand-new version of td-client-java 0.6.0? This will fail immediately upon unauthorized error.

**Comment by xerial** [comment]
Let me close this ticket since this is already fixed in the latest version.
