### ISSUE TITLE
tdJob.getResultSchema().get() doesn't return schema

### ISSUE THREAD

**Issue by kalu44i** [treasure-data/td-client-java#15]
Hi Muga!

When I get Result Schema's String from TDJob, it returns not expected result (empty value)
```
TDJob tdJob = client.jobInfo(jobId);
String schemaStr = tdJob.getResultSchema().get();
```
I expect to get this: ```[[\"d\", \"string\"], [\"_c1\", \"bigint\"]]```

I tried to get JobInfo using curl. It returns json which contains ```"hive_result_schema"``` var with expected value, http://take.ms/gT9Qc
```
curl -H "AUTHORIZATION: TD1 5ea***8b723c132****0e7c054506afa****741f" \                                                   
  "http://api.treasuredata.com/v3/job/show/40645296"
```
Looks like``` tdJob.getResultSchema().get()``` returns nothing cause @JsonProperty in TDJob is difference from the appropriate header in result json.
```
 @JsonProperty("result_schema") Optional<String> resultSchema
```

Additional info: 
I use 0.6.1 version.

Thanks.

**Comment by xerial** [comment]
Thanks for reporting. I made a fix for this. @muga Could you review this fix? Thanks

**Comment by muga** [comment]
@xerial LGTM.

**Comment by xerial** [comment]
Deployed a fixed version 0.6.2

**Comment by kalu44i** [comment]
@xerial version 0.6.2 isn't downloaded by Maven. Could you inform when it is accessed, please?

**Comment by xerial** [comment]
Synchronization to the Maven central will take 10 or more minutes. And now it's available: 
http://repo1.maven.org/maven2/com/treasuredata/client/td-client/
