### ISSUE TITLE
Order of version in Maven

### ISSUE THREAD

**Issue by toru-takahashi** [treasure-data/td-client-java#57]
Currently, this maven repo is ordered by file name.
http://central.maven.org/maven2/com/treasuredata/client/td-client/
So, latest version (0.7.22) is located in the middle.
It makes us confused.

I recommend to order by updated data (release date).

Current: 0.6.0 -> ... -> 0.7.22 -> ... -> 0.7.9
Good: (latest) 0.7.22 -> ... -> 0.7.9 -> ... -> 0.6.0 (oldest)

**Comment by xerial** [comment]
@toru we have no control of these ordering in Maven central

**Comment by xerial** [comment]
How about using this url? http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.treasuredata.client%22%20AND%20a%3A%22td-client%22

And also the label in td-doc shows the latest version
